FROM oven/bun:latest AS build

WORKDIR /app

COPY front/package.json front/bun.lock ./
RUN bun install --frozen-lockfile

COPY front .
RUN bun run build

FROM oven/bun:latest AS production

WORKDIR /app

COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/node_modules ./node_modules

EXPOSE 3000

CMD ["bun", "run", "start"]
