node_url = "http://localhost:4321"
server_port = 4000
log_format = "full"
hyli_chain_id = 1337
eth_state_root = "0000000000000000000000000000000000000000000000000000000000000000"
bridge_cn = "hyperlane-bridge"
hyperlane_cn = "hyperlane"
token_cn = "oranj"
data_directory = "data/bridge-server"
noinit = false

# ContractListener / AutoProver
indexer_database_url = "postgresql://postgres:postgres@localhost:5432/hyli_indexer"
contract_listener_poll_interval_secs = 5
prover_tx_buffer_size = 0
prover_max_txs_per_proof = 10
prover_tx_working_window_size = 50
prover_idle_flush_interval_secs = 2
